version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      TELEGRAM_TOKEN: "6170146129:AAFIzKz1RCiCM56zMbjUklnrLrWDzxsBvtk"
      OPENAI_API_KEY: "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"
    volumes:
      - ./logs:/app/logs