version: '3'
services:
  myapp:
    build: .
    ports:
      - "9000:80"
    volumes:
      - ./logs:/app/logs
    environment:
      - TELEGRAM_TOKEN: "6038351834:AAHrRDBUteglTmvBGPEQjN1mor8_8Bm1Blk"
      - OPENAI_API_KEY: "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"
