version: '3'

services:
  bot:
    build: .
    container_name: juno_solar_assistants
    restart: always
    environment:
      TELEGRAM_TOKEN: ""
      OPENAI_API_KEY: ""
    volumes:
      - ./logs:/app/logs